services:
  etl:
    build:
      context: .
      dockerfile: ETL/Dockerfile

    container_name: ups_etl

    env_file:
      - .env

    environment:
      TZ: Asia/Makassar

    volumes:
      - ./ETL/logs:/app/logs