name: ups-airflow

services:
  airflow-metadb:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-metadb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 10
    restart: unless-stopped

  airflow:
    image: apache/airflow:3.1.8
    command: standalone
    depends_on:
      airflow-metadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-metadb:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Makassar
      AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL: "30"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: admin:admin
      TZ: Asia/Makassar
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./staging:/opt/airflow/staging
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  airflow-metadb-data: